### ISSUE TITLE
Repo housekeeping

### ISSUE THREAD

**Issue by davelab6** [FontBureau/fb-lexend#3]
- [x] Please add a `/README.md` 
- [x] Please add a `/OFL.txt`
- [x] Please move `build-lexend.py` into `/sources`
- [x] Please add all the missing test docs and proofs created in the last 4 months into `/docs`

**Comment by davelab6** [comment]
@sannorozco do you have any modest drawbot script or such that could build the images?

**Comment by sannorozco** [comment]
Locating the files, pushing soon and closing this issue.

**Comment by sannorozco** [comment]
Added promos.
